import type { Metadata } from "next";

import { Footer, Navbar } from "@/components";

export const metadata: Metadata = {
  title: "V Business Chat 🤝",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      {/* position relative is for the hero background svg that has a absolute position. */}
      <div className="relative px-6 lg:mx-auto xl:max-w-[86rem] lg:space-y-5">
        <Navbar />

        {children}

        <Footer />
      </div>
    </>
  );
}
